name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # --- PASUL PENTRU LINUX ---
    - name: Install Linux Dependencies (SFML Build + Valgrind)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y \
          ninja-build \
          valgrind \
          xdotool \
          openbox \
          libxkbcommon-x11-0 \
          libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 \
          libgl1-mesa-dev \
          libx11-dev \
          libxrandr-dev \
          libudev-dev \
          libopenal-dev \
          libvorbis-dev \
          libflac-dev \
          libfreetype6-dev \
          libxcursor-dev \
          xvfb
        
        # https://github.com/llvm/llvm-project/issues/78354
        sudo sysctl vm.mmap_rnd_bits=28

    # --- PASUL PENTRU MACOS ---
    - name: Install macOS Dependencies (SFML)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install sfml

    # --- PASUL PENTRU WINDOWS ---
    - name: Install Windows Dependencies (SFML)
      shell: bash
      if: runner.os == 'Windows'
      run: |
        choco install sfml.devel -y

    # Pasul Clang (lăsat comentat cum era în șablonul tău)
    # - name: Install Clang ${{ matrix.clang_ver }}
    #   if: runner.os == 'Linux' && matrix.runs_msan == true
    #   ...